# supported strategies: memory/redis/redis-spawn
# the redis-spawn spawns an instance of redis-server, and connects to it
# through a unix-domain socket
strategy: redis-spawn

# redis config, used when strategy = redis
redis:
  host: 127.0.0.1
  port: 6379
